# ─────────────────────────────────────────────
# pibl.conf  — Configuración del PIBL
# ─────────────────────────────────────────────

# Puerto en el que escucha el proxy (80 o 8080)
port = 8080

# Archivo de log
log_file = ./logs/pibl.log

# Servidores backend (formato host:puerto)
# Agregar una línea por cada servidor
backend = 127.0.0.1:9001
backend = 127.0.0.1:9002
backend = 127.0.0.1:9003
